[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
program-a = "ALkpavDZFcbRNjZn8cf3ptLfT9DSYQ3hkKBxeZPAXYz2"
program-b = "G8pztLe793X3k3u8FGVdyM9aBaqY8UPYuknzKVyay9N4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
